// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoYOhdV9faGAnkJdLSKEVsqw3nQ78uFmU',
    appId: '1:833691308611:web:d2fb0624a3f16459fc3af6',
    messagingSenderId: '833691308611',
    projectId: 'playz-7ba44',
    authDomain: 'playz-7ba44.firebaseapp.com',
    storageBucket: 'playz-7ba44.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGq6S8SZwaJVuO_7DRYgktKsuXsu0M4eo',
    appId: '1:833691308611:android:df97bce1102565aefc3af6',
    messagingSenderId: '833691308611',
    projectId: 'playz-7ba44',
    storageBucket: 'playz-7ba44.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBW0GM1ufaOahOU1OiGkXao0OvIey4UHx0',
    appId: '1:833691308611:ios:1001e9ba31679ecdfc3af6',
    messagingSenderId: '833691308611',
    projectId: 'playz-7ba44',
    storageBucket: 'playz-7ba44.appspot.com',
    iosBundleId: 'com.example.playz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBW0GM1ufaOahOU1OiGkXao0OvIey4UHx0',
    appId: '1:833691308611:ios:6dd3300461bf8752fc3af6',
    messagingSenderId: '833691308611',
    projectId: 'playz-7ba44',
    storageBucket: 'playz-7ba44.appspot.com',
    iosBundleId: 'com.example.playz.RunnerTests',
  );
}
